# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4358080aa200bfb2087097e521bfe235c721abc02864aacf497a2f74d4655f5a65652b8c06a00c6cd233c60fcc87f9bf55121193024e93332f5f1bba73fc49ca

test:
  secret_key_base: e3b53cd1cbabb24a30b4a516954b5e843c7b26e2daf4024968c7bb8bef7f1d53c049294395eef4d2c239ca439c58fd779876c07cadbaead9f9630fcb5c4c4728

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
